DECLARE 
	CONTADOR     NUMBER(1);
	NOMBRE_JUEGO VARCHAR2(10) := 'JUEGO';
	NOMBRE_FINAL VARCHAR2(10);
BEGIN
	DELETE FROM PLANTILLAS;
	
	FOR CONTADOR IN 1..4 LOOP
		NOMBRE_FINAL := NOMBRE_JUEGO || '_' || TO_CHAR(CONTADOR);
		INSERT INTO PLANTILLAS 
		 (ID, NOMBRE, NIVEL)
        VALUES(CONTADOR, NOMBRE_FINAL, CONTADOR);
	END LOOP;
	

END;
/