DECLARE
    ID_PLANTILLA NUMBER(38) := 3;

BEGIN 
		delete pistas
		where IDPLANTILLA = 3;
		
	 /*JUEGO muy dificil*/
	 	INSERT INTO PISTAS
	 		(IDPOSICION, IDPLANTILLA, VALOR)
	 	VALUES(3, ID_PLANTILLA, 2);

		INSERT INTO PISTAS
	 		(IDPOSICION, IDPLANTILLA, VALOR)
	 	VALUES(7, ID_PLANTILLA, 6);

	 	INSERT INTO PISTAS
	 		(IDPOSICION, IDPLANTILLA, VALOR)
	 	VALUES(10, ID_PLANTILLA, 5);

	 	INSERT INTO PISTAS
	 		(IDPOSICION, IDPLANTILLA, VALOR)
	 	VALUES(13, ID_PLANTILLA, 7);

	 	INSERT INTO PISTAS
	 		(IDPOSICION, IDPLANTILLA, VALOR)
	 	VALUES(14, ID_PLANTILLA, 8);

	 	INSERT INTO PISTAS
	 		(IDPOSICION, IDPLANTILLA, VALOR)
	 	VALUES(15, ID_PLANTILLA, 9);

	 	INSERT INTO PISTAS
	 		(IDPOSICION, IDPLANTILLA, VALOR)
	 	VALUES(28, ID_PLANTILLA, 2);

	 	INSERT INTO PISTAS
	 		(IDPOSICION, IDPLANTILLA, VALOR)
	 	VALUES(29, ID_PLANTILLA, 1);

	 	INSERT INTO PISTAS
	 		(IDPOSICION, IDPLANTILLA, VALOR)
	 	VALUES(30, ID_PLANTILLA, 8);

	 	INSERT INTO PISTAS
	 		(IDPOSICION, IDPLANTILLA, VALOR)
	 	VALUES(36, ID_PLANTILLA, 4);

	 	INSERT INTO PISTAS
	 		(IDPOSICION, IDPLANTILLA, VALOR)
	 	VALUES(38, ID_PLANTILLA, 6);

	 	INSERT INTO PISTAS
	 		(IDPOSICION, IDPLANTILLA, VALOR)
	 	VALUES(41, ID_PLANTILLA, 5);

	 	INSERT INTO PISTAS
	 		(IDPOSICION, IDPLANTILLA, VALOR)
	 	VALUES(42, ID_PLANTILLA, 4);

	 	INSERT INTO PISTAS
	 		(IDPOSICION, IDPLANTILLA, VALOR)
	 	VALUES(45, ID_PLANTILLA, 2);

	 	INSERT INTO PISTAS
	 		(IDPOSICION, IDPLANTILLA, VALOR)
	 	VALUES(47, ID_PLANTILLA, 5);

	 	INSERT INTO PISTAS
	 		(IDPOSICION, IDPLANTILLA, VALOR)
	 	VALUES(48, ID_PLANTILLA, 9);

	 	INSERT INTO PISTAS
	 		(IDPOSICION, IDPLANTILLA, VALOR)
	 	VALUES(51, ID_PLANTILLA, 1);

	 	INSERT INTO PISTAS
	 		(IDPOSICION, IDPLANTILLA, VALOR)
	 	VALUES(54, ID_PLANTILLA, 8);

	 	INSERT INTO PISTAS
	 		(IDPOSICION, IDPLANTILLA, VALOR)
	 	VALUES(55, ID_PLANTILLA, 3);

	 	INSERT INTO PISTAS
	 		(IDPOSICION, IDPLANTILLA, VALOR)
	 	VALUES(61, ID_PLANTILLA, 2);

	 	INSERT INTO PISTAS
	 		(IDPOSICION, IDPLANTILLA, VALOR)
	 	VALUES(63, ID_PLANTILLA, 6);

	 	INSERT INTO PISTAS
	 		(IDPOSICION, IDPLANTILLA, VALOR)
	 	VALUES(65, ID_PLANTILLA, 4);

	 	INSERT INTO PISTAS
	 		(IDPOSICION, IDPLANTILLA, VALOR)
	 	VALUES(67, ID_PLANTILLA, 5);

	 	INSERT INTO PISTAS
	 		(IDPOSICION, IDPLANTILLA, VALOR)
	 	VALUES(69, ID_PLANTILLA, 3);

	 	INSERT INTO PISTAS
	 		(IDPOSICION, IDPLANTILLA, VALOR)
	 	VALUES(70, ID_PLANTILLA, 8);

	 	INSERT INTO PISTAS
	 		(IDPOSICION, IDPLANTILLA, VALOR)
	 	VALUES(72, ID_PLANTILLA, 9);

	 	INSERT INTO PISTAS
	 		(IDPOSICION, IDPLANTILLA, VALOR)
	 	VALUES(73, ID_PLANTILLA, 9);

	 	INSERT INTO PISTAS
	 		(IDPOSICION, IDPLANTILLA, VALOR)
	 	VALUES(77, ID_PLANTILLA, 6);

	 	INSERT INTO PISTAS
	 		(IDPOSICION, IDPLANTILLA, VALOR)
	 	VALUES(79, ID_PLANTILLA, 5);

	 	INSERT INTO PISTAS
	 		(IDPOSICION, IDPLANTILLA, VALOR)
	 	VALUES(80, ID_PLANTILLA, 3);































	 	
	 
END;
/