DECLARE
    ID_PLANTILLA NUMBER(38) := 1;

BEGIN 
		delete pistas
		where IDPLANTILLA = 1;
		
	 /*JUEGO FACIL*/
	 	INSERT INTO PISTAS
	 		(IDPOSICION, IDPLANTILLA, VALOR)
	 	VALUES(2, ID_PLANTILLA, 2);

	 	INSERT INTO PISTAS
	 		(IDPOSICION, IDPLANTILLA, VALOR)
	 	VALUES(3, ID_PLANTILLA, 3);

	 	INSERT INTO PISTAS
	 		(IDPOSICION, IDPLANTILLA, VALOR)
	 	VALUES(5, ID_PLANTILLA, 4);
	 	
	 	INSERT INTO PISTAS
	 		(IDPOSICION, IDPLANTILLA, VALOR)
	 	VALUES(6, ID_PLANTILLA, 7);

	 	INSERT INTO PISTAS
	 		(IDPOSICION, IDPLANTILLA, VALOR)
	 	VALUES(7, ID_PLANTILLA, 8);

	 	INSERT INTO PISTAS
	 		(IDPOSICION, IDPLANTILLA, VALOR)
	 	VALUES(11, ID_PLANTILLA, 5);

	 	INSERT INTO PISTAS
	 		(IDPOSICION, IDPLANTILLA, VALOR)
	 	VALUES(12, ID_PLANTILLA, 6);

		INSERT INTO PISTAS
	 		(IDPOSICION, IDPLANTILLA, VALOR)
	 	VALUES(16, ID_PLANTILLA, 4);

	 	INSERT INTO PISTAS
	 		(IDPOSICION, IDPLANTILLA, VALOR)
	 	VALUES(18, ID_PLANTILLA, 7);

	 	INSERT INTO PISTAS
	 		(IDPOSICION, IDPLANTILLA, VALOR)
	 	VALUES(22, ID_PLANTILLA, 6);

	 	INSERT INTO PISTAS
	 		(IDPOSICION, IDPLANTILLA, VALOR)
	 	VALUES(25, ID_PLANTILLA, 5);
	 	
	 	INSERT INTO PISTAS
	 		(IDPOSICION, IDPLANTILLA, VALOR)
	 	VALUES(26, ID_PLANTILLA, 2);

	 	INSERT INTO PISTAS
	 		(IDPOSICION, IDPLANTILLA, VALOR)
	 	VALUES(27, ID_PLANTILLA, 9);
	 	
	 	INSERT INTO PISTAS
	 		(IDPOSICION, IDPLANTILLA, VALOR)
	 	VALUES(31, ID_PLANTILLA, 3);
	 	
	 	INSERT INTO PISTAS
	 		(IDPOSICION, IDPLANTILLA, VALOR)
	 	VALUES(35, ID_PLANTILLA, 4);
	 	
	 	INSERT INTO PISTAS
	 		(IDPOSICION, IDPLANTILLA, VALOR)
	 	VALUES(36, ID_PLANTILLA, 5);
	 	
	 	INSERT INTO PISTAS
	 		(IDPOSICION, IDPLANTILLA, VALOR)
	 	VALUES(37, ID_PLANTILLA, 3);
	 	
	 	INSERT INTO PISTAS
	 		(IDPOSICION, IDPLANTILLA, VALOR)
	 	VALUES(38, ID_PLANTILLA, 6);

	 	INSERT INTO PISTAS
	 		(IDPOSICION, IDPLANTILLA, VALOR)
	 	VALUES(40, ID_PLANTILLA, 2);

	 	INSERT INTO PISTAS
	 		(IDPOSICION, IDPLANTILLA, VALOR)
	 	VALUES(45, ID_PLANTILLA, 8);

	 	INSERT INTO PISTAS
	 		(IDPOSICION, IDPLANTILLA, VALOR)
	 	VALUES(46, ID_PLANTILLA, 4);

	 	INSERT INTO PISTAS
	 		(IDPOSICION, IDPLANTILLA, VALOR)
	 	VALUES(50, ID_PLANTILLA, 7);

	 	INSERT INTO PISTAS
	 		(IDPOSICION, IDPLANTILLA, VALOR)
	 	VALUES(51, ID_PLANTILLA, 5);

	 	INSERT INTO PISTAS
	 		(IDPOSICION, IDPLANTILLA, VALOR)
	 	VALUES(52, ID_PLANTILLA, 2);

	 	INSERT INTO PISTAS
	 		(IDPOSICION, IDPLANTILLA, VALOR)
	 	VALUES(54, ID_PLANTILLA, 3);

	 	INSERT INTO PISTAS
	 		(IDPOSICION, IDPLANTILLA, VALOR)
	 	VALUES(56, ID_PLANTILLA, 4);

	 	INSERT INTO PISTAS
	 		(IDPOSICION, IDPLANTILLA, VALOR)
	 	VALUES(57, ID_PLANTILLA, 2);

	 	INSERT INTO PISTAS
	 		(IDPOSICION, IDPLANTILLA, VALOR)
	 	VALUES(58, ID_PLANTILLA, 7);

	 	INSERT INTO PISTAS
	 		(IDPOSICION, IDPLANTILLA, VALOR)
	 	VALUES(59, ID_PLANTILLA, 5);

	 	INSERT INTO PISTAS
	 		(IDPOSICION, IDPLANTILLA, VALOR)
	 	VALUES(61, ID_PLANTILLA, 3);

	 	INSERT INTO PISTAS
	 		(IDPOSICION, IDPLANTILLA, VALOR)
	 	VALUES(64, ID_PLANTILLA, 8);

	 	INSERT INTO PISTAS
	 		(IDPOSICION, IDPLANTILLA, VALOR)
	 	VALUES(67, ID_PLANTILLA, 4);

	 	INSERT INTO PISTAS
	 		(IDPOSICION, IDPLANTILLA, VALOR)
	 	VALUES(68, ID_PLANTILLA, 3);

	 	INSERT INTO PISTAS
	 		(IDPOSICION, IDPLANTILLA, VALOR)
	 	VALUES(73, ID_PLANTILLA, 5);

	 	INSERT INTO PISTAS
	 		(IDPOSICION, IDPLANTILLA, VALOR)
	 	VALUES(76, ID_PLANTILLA, 8);

	 	INSERT INTO PISTAS
	 		(IDPOSICION, IDPLANTILLA, VALOR)
	 	VALUES(77, ID_PLANTILLA, 6);

	 	INSERT INTO PISTAS
	 		(IDPOSICION, IDPLANTILLA, VALOR)
	 	VALUES(79, ID_PLANTILLA, 7);

	 	INSERT INTO PISTAS
	 		(IDPOSICION, IDPLANTILLA, VALOR)
	 	VALUES(81, ID_PLANTILLA, 4);
	 	
	 
END;
/