DECLARE
    ID_PLANTILLA NUMBER(38) := 2;

BEGIN
		delete pistas
		where IDPLANTILLA = 2;
		
	 /*JUEGO MEDIO*/
	 	INSERT INTO PISTAS
	 		(IDPOSICION, IDPLANTILLA, VALOR)
	 	VALUES(3, ID_PLANTILLA, 4);

	 	INSERT INTO PISTAS
	 		(IDPOSICION, IDPLANTILLA, VALOR)
	 	VALUES(4, ID_PLANTILLA, 2);

	 	INSERT INTO PISTAS
	 		(IDPOSICION, IDPLANTILLA, VALOR)
	 	VALUES(5, ID_PLANTILLA, 7);

	 	INSERT INTO PISTAS
	 		(IDPOSICION, IDPLANTILLA, VALOR)
	 	VALUES(10, ID_PLANTILLA, 8);

	 	INSERT INTO PISTAS
	 		(IDPOSICION, IDPLANTILLA, VALOR)
	 	VALUES(11, ID_PLANTILLA, 2);

	 	INSERT INTO PISTAS
	 		(IDPOSICION, IDPLANTILLA, VALOR)
	 	VALUES(15, ID_PLANTILLA, 6);

	 	INSERT INTO PISTAS
	 		(IDPOSICION, IDPLANTILLA, VALOR)
	 	VALUES(16, ID_PLANTILLA, 7);

	 	INSERT INTO PISTAS
	 		(IDPOSICION, IDPLANTILLA, VALOR)
	 	VALUES(24, ID_PLANTILLA, 9);

	 	INSERT INTO PISTAS
	 		(IDPOSICION, IDPLANTILLA, VALOR)
	 	VALUES(25, ID_PLANTILLA, 3);
	 	
	 	INSERT INTO PISTAS
	 		(IDPOSICION, IDPLANTILLA, VALOR)
	 	VALUES(27, ID_PLANTILLA, 2);

	 	INSERT INTO PISTAS
	 		(IDPOSICION, IDPLANTILLA, VALOR)
	 	VALUES(30, ID_PLANTILLA, 8);

	 	INSERT INTO PISTAS
	 		(IDPOSICION, IDPLANTILLA, VALOR)
	 	VALUES(31, ID_PLANTILLA, 6);

	 	INSERT INTO PISTAS
	 		(IDPOSICION, IDPLANTILLA, VALOR)
	 	VALUES(35, ID_PLANTILLA, 2);

	 	INSERT INTO PISTAS
	 		(IDPOSICION, IDPLANTILLA, VALOR)
	 	VALUES(36, ID_PLANTILLA, 3);

	 	INSERT INTO PISTAS
	 		(IDPOSICION, IDPLANTILLA, VALOR)
	 	VALUES(39, ID_PLANTILLA, 3);

	 	INSERT INTO PISTAS
	 		(IDPOSICION, IDPLANTILLA, VALOR)
	 	VALUES(45, ID_PLANTILLA, 8);

	 	INSERT INTO PISTAS
	 		(IDPOSICION, IDPLANTILLA, VALOR)
	 	VALUES(46, ID_PLANTILLA, 5);

	 	INSERT INTO PISTAS
	 		(IDPOSICION, IDPLANTILLA, VALOR)
	 	VALUES(50, ID_PLANTILLA, 9);

	 	INSERT INTO PISTAS
	 		(IDPOSICION, IDPLANTILLA, VALOR)
	 	VALUES(53, ID_PLANTILLA, 7);

	 	INSERT INTO PISTAS
	 		(IDPOSICION, IDPLANTILLA, VALOR)
	 	VALUES(55, ID_PLANTILLA, 2);

	 	INSERT INTO PISTAS
	 		(IDPOSICION, IDPLANTILLA, VALOR)
	 	VALUES(59, ID_PLANTILLA, 1);

	 	INSERT INTO PISTAS
	 		(IDPOSICION, IDPLANTILLA, VALOR)
	 	VALUES(63, ID_PLANTILLA, 7);

	 	INSERT INTO PISTAS
	 		(IDPOSICION, IDPLANTILLA, VALOR)
	 	VALUES(64, ID_PLANTILLA, 6);

	 	INSERT INTO PISTAS
	 		(IDPOSICION, IDPLANTILLA, VALOR)
	 	VALUES(67, ID_PLANTILLA, 7);
	 	
	 	INSERT INTO PISTAS
	 		(IDPOSICION, IDPLANTILLA, VALOR)
	 	VALUES(68, ID_PLANTILLA, 2);

	 	INSERT INTO PISTAS
	 		(IDPOSICION, IDPLANTILLA, VALOR)
	 	VALUES(70, ID_PLANTILLA, 9);

	 	INSERT INTO PISTAS
	 		(IDPOSICION, IDPLANTILLA, VALOR)
	 	VALUES(71, ID_PLANTILLA, 3);

	 	INSERT INTO PISTAS
	 		(IDPOSICION, IDPLANTILLA, VALOR)
	 	VALUES(72, ID_PLANTILLA, 1);

	 	INSERT INTO PISTAS
	 		(IDPOSICION, IDPLANTILLA, VALOR)
	 	VALUES(73, ID_PLANTILLA, 3);

	 	INSERT INTO PISTAS
	 		(IDPOSICION, IDPLANTILLA, VALOR)
	 	VALUES(76, ID_PLANTILLA, 9);

	 	INSERT INTO PISTAS
	 		(IDPOSICION, IDPLANTILLA, VALOR)
	 	VALUES(77, ID_PLANTILLA, 6);
END;
/