DECLARE
    ID_PLANTILLA NUMBER(38) := 4;

BEGIN
		delete pistas
		where IDPLANTILLA = 4;

	 /*JUEGO PRESENTACION*/
	 	INSERT INTO PISTAS (IDPOSICION, IDPLANTILLA, VALOR) VALUES(3, ID_PLANTILLA, 6);
    INSERT INTO PISTAS (IDPOSICION, IDPLANTILLA, VALOR) VALUES(6, ID_PLANTILLA, 2);
    INSERT INTO PISTAS (IDPOSICION, IDPLANTILLA, VALOR) VALUES(7, ID_PLANTILLA, 3);
    INSERT INTO PISTAS (IDPOSICION, IDPLANTILLA, VALOR) VALUES(9, ID_PLANTILLA, 4);
    INSERT INTO PISTAS (IDPOSICION, IDPLANTILLA, VALOR) VALUES(10, ID_PLANTILLA, 9);
    INSERT INTO PISTAS (IDPOSICION, IDPLANTILLA, VALOR) VALUES(12, ID_PLANTILLA, 4);
    INSERT INTO PISTAS (IDPOSICION, IDPLANTILLA, VALOR) VALUES(13, ID_PLANTILLA, 7);
    INSERT INTO PISTAS (IDPOSICION, IDPLANTILLA, VALOR) VALUES(14, ID_PLANTILLA, 5);
    INSERT INTO PISTAS (IDPOSICION, IDPLANTILLA, VALOR) VALUES(17, ID_PLANTILLA, 8);
    INSERT INTO PISTAS (IDPOSICION, IDPLANTILLA, VALOR) VALUES(18, ID_PLANTILLA, 2);
    INSERT INTO PISTAS (IDPOSICION, IDPLANTILLA, VALOR) VALUES(21, ID_PLANTILLA, 8);
    INSERT INTO PISTAS (IDPOSICION, IDPLANTILLA, VALOR) VALUES(24, ID_PLANTILLA, 6);
    INSERT INTO PISTAS (IDPOSICION, IDPLANTILLA, VALOR) VALUES(27, ID_PLANTILLA, 5);
    INSERT INTO PISTAS (IDPOSICION, IDPLANTILLA, VALOR) VALUES(30, ID_PLANTILLA, 3);
    INSERT INTO PISTAS (IDPOSICION, IDPLANTILLA, VALOR) VALUES(35, ID_PLANTILLA, 4);
    INSERT INTO PISTAS (IDPOSICION, IDPLANTILLA, VALOR) VALUES(37, ID_PLANTILLA, 2);
    INSERT INTO PISTAS (IDPOSICION, IDPLANTILLA, VALOR) VALUES(40, ID_PLANTILLA, 4);
    INSERT INTO PISTAS (IDPOSICION, IDPLANTILLA, VALOR) VALUES(43, ID_PLANTILLA, 8);
    INSERT INTO PISTAS (IDPOSICION, IDPLANTILLA, VALOR) VALUES(44, ID_PLANTILLA, 3);
    INSERT INTO PISTAS (IDPOSICION, IDPLANTILLA, VALOR) VALUES(46, ID_PLANTILLA, 4);
    INSERT INTO PISTAS (IDPOSICION, IDPLANTILLA, VALOR) VALUES(48, ID_PLANTILLA, 7);
    INSERT INTO PISTAS (IDPOSICION, IDPLANTILLA, VALOR) VALUES(49, ID_PLANTILLA, 5);
    INSERT INTO PISTAS (IDPOSICION, IDPLANTILLA, VALOR) VALUES(58, ID_PLANTILLA, 6);
    INSERT INTO PISTAS (IDPOSICION, IDPLANTILLA, VALOR) VALUES(63, ID_PLANTILLA, 8);
    INSERT INTO PISTAS (IDPOSICION, IDPLANTILLA, VALOR) VALUES(64, ID_PLANTILLA, 7);
    INSERT INTO PISTAS (IDPOSICION, IDPLANTILLA, VALOR) VALUES(68, ID_PLANTILLA, 2);
    INSERT INTO PISTAS (IDPOSICION, IDPLANTILLA, VALOR) VALUES(70, ID_PLANTILLA, 4);
    INSERT INTO PISTAS (IDPOSICION, IDPLANTILLA, VALOR) VALUES(71, ID_PLANTILLA, 5);
    INSERT INTO PISTAS (IDPOSICION, IDPLANTILLA, VALOR) VALUES(72, ID_PLANTILLA, 3);
    INSERT INTO PISTAS (IDPOSICION, IDPLANTILLA, VALOR) VALUES(76, ID_PLANTILLA, 3);
    INSERT INTO PISTAS (IDPOSICION, IDPLANTILLA, VALOR) VALUES(77, ID_PLANTILLA, 7);
    INSERT INTO PISTAS (IDPOSICION, IDPLANTILLA, VALOR) VALUES(80, ID_PLANTILLA, 6);
    INSERT INTO PISTAS (IDPOSICION, IDPLANTILLA, VALOR) VALUES(81, ID_PLANTILLA, 9);


END;
/
